export const SCOPE_APPLICATION_PREFIX = "CIRRAS_CLAIMS.";

export const SCOPES_UI = {
    //CREATE_CLAIM: `${SCOPE_APPLICATION_PREFIX}CREATE_CLAIM`, //remove
    CREATE_CALCULATION: `${SCOPE_APPLICATION_PREFIX}CREATE_CALCULATION`,
    //DELETE_CLAIM: `${SCOPE_APPLICATION_PREFIX}DELETE_CLAIM`, //remove
    DELETE_CALCULATION: `${SCOPE_APPLICATION_PREFIX}DELETE_CALCULATION`,
    //GET_CLAIM: `${SCOPE_APPLICATION_PREFIX}GET_CLAIM`, //remove
    GET_CALCULATION: `${SCOPE_APPLICATION_PREFIX}GET_CALCULATION`,
    GET_CODE_TABLES: `${SCOPE_APPLICATION_PREFIX}GET_CODE_TABLES`,
    SEARCH_CLAIMS: `${SCOPE_APPLICATION_PREFIX}SEARCH_CLAIMS`,
    SEARCH_CALCULATIONS: `${SCOPE_APPLICATION_PREFIX}SEARCH_CALCULATIONS`,
    //UPDATE_CLAIM: `${SCOPE_APPLICATION_PREFIX}UPDATE_CLAIM`,//remove
    UPDATE_CALCULATION: `${SCOPE_APPLICATION_PREFIX}UPDATE_CALCULATION`,
    REFRESH_DATA: `${SCOPE_APPLICATION_PREFIX}REFRESH_DATA`,
    PRINT_CALCULATION: `${SCOPE_APPLICATION_PREFIX}PRINT_CALCULATION`,
    FINALIZE_CALCULATION: `${SCOPE_APPLICATION_PREFIX}FINALIZE_CALCULATION`,
    REPLACE_CALCULATION: `${SCOPE_APPLICATION_PREFIX}REPLACE_CALCULATION`,
    GET_TOP_LEVEL: `${SCOPE_APPLICATION_PREFIX}GET_TOP_LEVEL`
};

export const ROLES_UI = {
  CLAIMS_MONITOR: `${SCOPE_APPLICATION_PREFIX}CLAIMS_MONITOR`,
  CLAIMS_SUPER_ADMIN: `${SCOPE_APPLICATION_PREFIX}CLAIMS_SUPER_ADMIN`,
  CLAIMS_MANAGER: `${SCOPE_APPLICATION_PREFIX}CLAIMS_MANAGER`,
  CLAIMS_VIEWER: `${SCOPE_APPLICATION_PREFIX}CLAIMS_VIEWER`,
};

export const ROUTE_SCOPES = {
  LANDING                               : [SCOPES_UI.GET_TOP_LEVEL, SCOPES_UI.GET_CODE_TABLES, SCOPES_UI.SEARCH_CALCULATIONS],
  CLAIM                                 : [SCOPES_UI.SEARCH_CLAIMS],
  CALCULATION                           : [SCOPES_UI.SEARCH_CALCULATIONS],
  CALCULATION_DETAIL                    : [SCOPES_UI.GET_CALCULATION, SCOPES_UI.GET_CODE_TABLES],
  CALCULATION_PRINTOUT                  : [SCOPES_UI.GET_CALCULATION, SCOPES_UI.GET_CODE_TABLES]
}
