apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '#{NAMESPACE}#'
  name: 'pit-claim-ui-deployment-#{ENV}#'
spec:
  selector:
    matchLabels:
      app: pit-claim-ui-#{ENV}#
  replicas: 1
  template:
    metadata:
      labels:
        app: pit-claim-ui-#{ENV}#
        project: brmb-pit-claim-#{ENV}#        
    spec:
      serviceAccountName: #{LICENSE_PLATE}#-vault
      containers:
        - name: container
          image: '#{IMAGE_BY_DIGEST}#'
          imagePullPolicy: Always
          # command:
          #   ['sh', '-c']
          # args:
          #   ['. /vault/secrets/env && catalina.sh run']
          # ports:
          #   - containerPort: #{TOMCAT_PORT}#
          #     protocol: TCP
          env:
            - name: TOMCAT_PORT
              valueFrom: 
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: TOMCAT_PORT
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: BASE_URL
            - name: CIRRAS_CLAIMS_REST_URI
              valueFrom:
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: CIRRAS_CLAIMS_REST_URI
            - name: PIT_UNDERWRITING_UI_URL
              valueFrom:
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: PIT_UNDERWRITING_UI_URL
            - name: WEBADE_OAUTH2_AUTHORIZE_URL
              valueFrom:
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: WEBADE_OAUTH2_AUTHORIZE_URL
            - name: WEBADE_OAUTH2_ENABLE_CHECKTOKEN
              valueFrom:
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: WEBADE_OAUTH2_ENABLE_CHECKTOKEN
            - name: UI_CHECKTOKEN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: UI_CHECKTOKEN_ENDPOINT
            - name: WEBADE_OAUTH2_SCOPES
              valueFrom:
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: WEBADE_OAUTH2_SCOPES
            - name: WEBADE_OAUTH2_SITEMINDER_URL
              valueFrom:
                configMapKeyRef:
                  name: pit-claim-ui-config-#{ENV}#
                  key: WEBADE_OAUTH2_SITEMINDER_URL
            - name: APPLICATION_ENVIRONMENT_NAME      
              value: #{ENV}#
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /pub/pit-claim/
              port: #{TOMCAT_PORT}#
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 150m
              memory: 400Mi 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
